---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Remove default nginx config
  file:
    path: "{{ nginx_conf_path }}"
    state: absent

- name: get file names to copy
  command: "ls {{ local_nginx_conf_path }}"
  register: files_to_copy
  delegate_to: localhost

# Nginx setup.
- name: Copy nginx configuration in place.
  copy:
    src: "{{ local_nginx_conf_path }}/{{ item }}"
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0755
  with_items: 
    - "{{ files_to_copy.stdout_lines }}"
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
