---
# Variable setup.
- name: "Get temp dir"
  tempfile:
    state: directory
  register: tempdir
  delegate_to: localhost

- name: "Checkout nginx config"
  git:
    repo: "{{ nginx_config_git_repo }}"
    dest: "{{ tempdir.path }}"
  delegate_to: localhost

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Nginx setup.
- name: Copy nginx configuration in place.
  copy:
    src: "{{ tempdir.path }}"
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0755
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
